# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issues:
    types: [opened ]
  issue_comment:
    types: [created ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download
        run: aria2c "${{ github.event.issue.body }}"
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: File
          path: ${{ github.workspace }}
      - name: close-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "Download Finished.\nhttps://github.com/undefined-ux/GithubDownloader/actions/runs/${{github.run_id}}"
          body-includes: ${{ github.event.issue.body }}
